# This file was *autogenerated* from the file example.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
print "hello world"
print _sage_const_2 **_sage_const_3 

# Calculates A
def fun_one(P,r,t):
    A = P + t + r**_sage_const_2 
    return A
    
# Calculates amount invested
def fun_two(P,r,t,n):
    A = t*(_sage_const_1 +r/n)**(n*t**_sage_const_2 )
    return A
# Calculates amount invested (contin)
# Calculates amount invested (contin)
def fun_three(P,r,t):
    A = P*e**(r*t)
    return _sage_const_2 *A*A
