# This file was *autogenerated* from the file variable_simplify.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6)#defines variables and function




var('y,x,x_0,x_1,x_2,h_1,h_2,f_0,f_1,f_2,d,dd,ddd')

# p(x) =((x-x_1)*(x-x_2)*(f_0))/((x_0-x_1)*(x_0-x_2))+((x-x_0)*(x-x_2)*(f_1))/((x_1-x_0)*(x_1-x_2))+((x-x_0)*(x-x_1)*(f_2))/((x_2-x_0)*(x_2-x_1))
__tmp__=var("x"); w = symbolic_expression((x-x_0)*(x-x_1)*(x-x_2)).function(x)
s = diff(w,x,_sage_const_1 )
ss = diff(w,x,_sage_const_2 )
__tmp__=var("x"); p = symbolic_expression(ddd*w(x) + d*s+ dd/_sage_const_6 *s + d/_sage_const_6 *ss).function(x)

#example
#p(x_1) or p(3)

print(diff(p,x,_sage_const_1 ))
