# This file was *autogenerated* from the file worksheet.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_12 = Integer(12); _sage_const_18 = Integer(18); _sage_const_27 = Integer(27)
from example import *

#attach("worksheet.sage")


#Sat 19 Nov 2016 08:42:37 AM CST





#Fri 18 Nov 2016 04:58:18 PM CST

print mysyeq(
	matrix([
		[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
		[_sage_const_8 ,_sage_const_4 ,_sage_const_2 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
		[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_8 ,_sage_const_4 ,_sage_const_2 ,_sage_const_1 ],
		[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_27 ,_sage_const_9 ,_sage_const_3 ,_sage_const_1 ],
		[_sage_const_12 ,_sage_const_4 ,_sage_const_1 ,_sage_const_0 ,-_sage_const_12 ,-_sage_const_4 ,-_sage_const_1 ,_sage_const_0 ],
		[_sage_const_0 ,_sage_const_2 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
		[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_18 ,_sage_const_2 ,_sage_const_0 ,_sage_const_0 ],
		[_sage_const_12 ,_sage_const_2 ,_sage_const_0 ,_sage_const_0 ,-_sage_const_12 ,-_sage_const_2 ,_sage_const_0 ,_sage_const_0 ]]),
	vector([_sage_const_0 ,_sage_const_1 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ]))

myapp(e*pi)


_sage_const_3 +_sage_const_3 



