# This file was *autogenerated* from the file ws.sage
from sage.all_cmdline import *   # import sage library
_sage_const_260p00 = RealNumber('260.00'); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_410p00 = RealNumber('410.00'); _sage_const_5403 = Integer(5403); _sage_const_12 = Integer(12); _sage_const_18 = Integer(18); _sage_const_300p00 = RealNumber('300.00'); _sage_const_13044 = Integer(13044); _sage_const_27 = Integer(27)#!/usr/bin/sage -python /home/dowewas2/Sage/calculator/ws.sage

import sys
from sage.all import *

# attach("ws.sage")
attach("example.sage")
print ("=====================================================")
print ("------------------Derek's Worksheet------------------")
print ("=====================================================")



#Sun 20 Nov 2016 05:47:26 PM CST

print (_sage_const_300p00 /_sage_const_6 )/_sage_const_2 
(_sage_const_300p00 /_sage_const_6 )/_sage_const_2 

_sage_const_410p00 /_sage_const_12 

_sage_const_410p00 /_sage_const_12 

_sage_const_260p00 /_sage_const_6 



myapp(-_sage_const_1  + sqrt(_sage_const_2 ))
myapp(_sage_const_5403 /_sage_const_13044 )


#Sat 19 Nov 2016 08:42:37 AM CST




#Fri 18 Nov 2016 04:58:18 PM CST

mysyeq(
	matrix([
		[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
		[_sage_const_8 ,_sage_const_4 ,_sage_const_2 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
		[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_8 ,_sage_const_4 ,_sage_const_2 ,_sage_const_1 ],
		[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_27 ,_sage_const_9 ,_sage_const_3 ,_sage_const_1 ],
		[_sage_const_12 ,_sage_const_4 ,_sage_const_1 ,_sage_const_0 ,-_sage_const_12 ,-_sage_const_4 ,-_sage_const_1 ,_sage_const_0 ],
		[_sage_const_0 ,_sage_const_2 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
		[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_18 ,_sage_const_2 ,_sage_const_0 ,_sage_const_0 ],
		[_sage_const_12 ,_sage_const_2 ,_sage_const_0 ,_sage_const_0 ,-_sage_const_12 ,-_sage_const_2 ,_sage_const_0 ,_sage_const_0 ]]),
	vector([_sage_const_0 ,_sage_const_1 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ]))

myapp(e*pi)


_sage_const_3 +_sage_const_3 



